import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../../components/tables/Navbar";
import { Fillers } from "../../components/tables/Fillers";
import Footer from '../../components/tables/Footer';

const Home: NextPage = ({ formID }: any) => {
  return (
    <div>
      <Head>
        <title>Form Builder Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={` w-full h-full `}>
        <Navbar />
        <div className="bg-white">
        <Fillers />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
