import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import AppContext from '../src/context/appContext'
// import  Login  from '../components/auth/Login'
import Image from 'next/image'
// import Register from '../components/auth/Register'
import {HiArrowRight} from 'react-icons/hi'
import Link from 'next/link';
import { TypeAnimation } from "react-type-animation";
import AOS from "aos";
import "aos/dist/aos.css"
const Home: NextPage = () => {  
useEffect(() => {
  AOS.init({
    disable: function () {
      var maxWidth = 768
      return window.innerWidth < maxWidth
    },
    duration: 800,
  })
}, [])



  return (
    <div className='bg-background h-screen w-screen  '>
      <Head>
        <title>Form Builder Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute right-0 opacity-20">
        <img src='/landing.png' className='h-screen object-none md:object-contain'/>
      </div>
      <div className='flex flex-col gap-8 md:gap-16 h-screen justify-center ml-4 md:ml-12 mr-4 md:mr-24 '>
      <div className=' text-2xl md:text-5xl font-semibold text-gray-400 font-arapey' data-aos="zoom-in-up">Hello there!</div>  
      <div className='text-2xl md:text-4xl font-bold delay-300 text-gray-400 font-arapey' data-aos="zoom-in-up">
        Welcome to
        <br /> 
        <span className='text-5xl md:text-7xl text-gray-400 font-extrabold'>Form Builder Application
        </span>
        
      </div>
      <div className='flex flex-col md:flex-row mt-32 md:mt-8 gap-10 md:gap-40 w-full justify-between'>
          <span className='text-3xl md:text-5xl font-bold delay-1000 text-rose-700 font-arapey' data-aos="zoom-in-right">Let&apos;s get you started...</span>
          <Link href={'/login'}>
            <button className="relative w-fit px-5 py-3 overflow-hidden font-medium text-lime-400 bg-transparent border border-lime-400 rounded-lg shadow-inner group delay-1000" data-aos="zoom-in-left">
          <span className="absolute top-0 left-0 w-0 h-0 transition-all duration-200 border-t-2 border-lime-400 group-hover:w-full ease"></span>
          <span className="absolute bottom-0 right-0 w-0 h-0 transition-all duration-200 border-b-2 border-lime-400 group-hover:w-full ease"></span>
          <span className="absolute top-0 left-0 w-full h-0 transition-all duration-300 delay-200 bg-lime-400 group-hover:h-full ease"></span>
          <span className="absolute bottom-0 left-0 w-full h-0 transition-all duration-300 delay-200 bg-lime-400 group-hover:h-full ease"></span>
          <span className="absolute inset-0 w-full h-full duration-300 delay-300 bg-lime-500 opacity-0 group-hover:opacity-100"></span>
          <span className='flex flex-row gap-1'>
          <span className="relative transition-colors duration-300 delay-200 group-hover:text-white font-bold text-base md:text-xl ease px-2">Proceed</span>
          <HiArrowRight size="1.75em" className='group-hover:text-white relative transition-colors duration-300 delay-200 ease'/>
          </span>
          </button>
          </Link>
        </div>           
      </div>         
    </div>
  )
}


export default Home
